In [1]:
# Import Census data and Geographies
# List of Geographies and codes: https://jtleider.github.io/censusdata/geographies.html
# switched the ACS5 file to get zip level data

# setup Census JSON feed
from census import Census
from us import states
c = Census("c99084947ed68bfbd3d7359ba2340346f7984e60")

# importing additional libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import sklearn

#  importing the censusdata and pandas modules, and setting some display options in pandas
import pandas as pd
import censusdata
pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.precision', 2)

# importing JSON to Pandas translator
import requests
import urllib.parse
from pandas.io.json import json_normalize

In [4]:
# B19058_002E - B19058. Public Assistance Income or Food Stamps/SNAP in the Past 12 Months for Households


c.acs5.us(('B19058_002E'))



# change to a dataframe using pandas

acsus_S = c.acs5.us(('B19058_002E'))


# create a single dataframe with all of the us level data
acs_usdf_S = pd.DataFrame(acsus_S)


acs_usdf_S

   B19058_002E us
0     1.58e+07  1

In [3]:
# export to csv combined raw data

acs_usdf_S.to_csv('./acs5_us_S.csv')

In [5]:
# B19058_002E - B19058. Public Assistance Income or Food Stamps/SNAP in the Past 12 Months for Households

c.acs5.zipcode(('B19058_002E'), Census.ALL) 

    
# change to a datafrom using pandas

acs5z_S = c.acs5.zipcode(('B19058_002E'), Census.ALL) 

# create a single dataframe with all of the zip level data
acs5zip_S = pd.DataFrame(acs5z_S)
acs5zip_S

       B19058_002E zip code tabulation area
0           3113.0                    00601
1           6165.0                    00602
2           8219.0                    00603
3           1030.0                    00606
4           4152.0                    00610
5          10682.0                    00612
6           1812.0                    00616
7           3483.0                    00617
8            986.0                    00622
9           5100.0                    00623
10          3547.0                    00624
11          5352.0                    00627
12           379.0                    00631
13          3305.0                    00637
14          3325.0                    00638
15          4342.0                    00641
16          3570.0                    00646
17           898.0                    00647
18          2291.0                    00650
19           481.0                    00652
20          2026.0                    00653
21          3251.0                    00656
22          6417.0                    00659
23          2292.0                    00660
24          6336.0                    00662
25          2819.0                    00664
26          4084.0                    00667
27          5073.0                    00669
28          1520.0                    00670
29          6592.0                    00674
...            ...                      ...
33090         30.0                    99786
33091         15.0                    99788
33092         31.0                    99789
33093          0.0                    99790
33094         17.0                    99791
33095       1059.0                    99801
33096         59.0                    99820
33097        137.0                    99824
33098          0.0                    99825
33099          7.0                    99826
33100        120.0                    99827
33101         63.0                    99829
33102         80.0                    99830
33103          0.0                    99832
33104        171.0                    99833
33105        404.0                    99835
33106          0.0                    99836
33107         22.0                    99840
33108          0.0                    99841
33109        965.0                    99901
33110          0.0                    99903
33111          4.0                    99918
33112         34.0                    99919
33113        110.0                    99921
33114         36.0                    99922
33115          0.0                    99923
33116         72.0                    99925
33117        161.0                    99926
33118         22.0                    99927
33119        170.0                    99929

[33120 rows x 2 columns]

In [6]:
# export to csv combined raw data

acs5zip_S.to_csv('./acs5_zip_S.csv')

In [7]:
# B19058_002E - B19058. Public Assistance Income or Food Stamps/SNAP in the Past 12 Months for Households


c.acs5.state_county(('B19058_002E'), states.AL.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.AK.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.AZ.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.AR.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.CA.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.CO.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.CT.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.DE.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.FL.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.GA.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.HI.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.ID.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.IL.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.IN.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.IA.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.KS.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.KY.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.LA.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.ME.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.MD.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.MA.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.MI.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.MN.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.MS.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.MO.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.MT.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.NE.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.NV.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.NH.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.NJ.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.NM.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.NY.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.NC.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.ND.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.OH.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.OK.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.OR.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.PA.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.RI.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.SC.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.SD.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.TN.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.TX.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.UT.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.VT.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.VA.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.WA.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.WV.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.WI.fips, Census.ALL) 
c.acs5.state_county(('B19058_002E'), states.WY.fips, Census.ALL) 


# change to a dataframe using pandas

countyAL = c.acs5.state_county(('B19058_002E'), states.AL.fips, Census.ALL) 
countyAK = c.acs5.state_county(('B19058_002E'), states.AK.fips, Census.ALL) 
countyAZ = c.acs5.state_county(('B19058_002E'), states.AZ.fips, Census.ALL) 
countyAR = c.acs5.state_county(('B19058_002E'), states.AR.fips, Census.ALL) 
countyCA = c.acs5.state_county(('B19058_002E'), states.CA.fips, Census.ALL) 
countyCO = c.acs5.state_county(('B19058_002E'), states.CO.fips, Census.ALL) 
countyCT = c.acs5.state_county(('B19058_002E'), states.CT.fips, Census.ALL) 
countyDE = c.acs5.state_county(('B19058_002E'), states.DE.fips, Census.ALL) 
countyFL = c.acs5.state_county(('B19058_002E'), states.FL.fips, Census.ALL) 
countyGA = c.acs5.state_county(('B19058_002E'), states.GA.fips, Census.ALL) 
countyHI = c.acs5.state_county(('B19058_002E'), states.HI.fips, Census.ALL) 
countyID = c.acs5.state_county(('B19058_002E'), states.ID.fips, Census.ALL) 
countyIL = c.acs5.state_county(('B19058_002E'), states.IL.fips, Census.ALL) 
countyIN = c.acs5.state_county(('B19058_002E'), states.IN.fips, Census.ALL) 
countyIA = c.acs5.state_county(('B19058_002E'), states.IA.fips, Census.ALL) 
countyKS = c.acs5.state_county(('B19058_002E'), states.KS.fips, Census.ALL) 
countyKY = c.acs5.state_county(('B19058_002E'), states.KY.fips, Census.ALL) 
countyLA = c.acs5.state_county(('B19058_002E'), states.LA.fips, Census.ALL) 
countyME = c.acs5.state_county(('B19058_002E'), states.ME.fips, Census.ALL) 
countyMD = c.acs5.state_county(('B19058_002E'), states.MD.fips, Census.ALL) 
countyMA = c.acs5.state_county(('B19058_002E'), states.MA.fips, Census.ALL) 
countyMI = c.acs5.state_county(('B19058_002E'), states.MI.fips, Census.ALL) 
countyMN = c.acs5.state_county(('B19058_002E'), states.MN.fips, Census.ALL) 
countyMS = c.acs5.state_county(('B19058_002E'), states.MS.fips, Census.ALL) 
countyMO = c.acs5.state_county(('B19058_002E'), states.MO.fips, Census.ALL) 
countyMT = c.acs5.state_county(('B19058_002E'), states.MT.fips, Census.ALL) 
countyNE = c.acs5.state_county(('B19058_002E'), states.NE.fips, Census.ALL) 
countyNV = c.acs5.state_county(('B19058_002E'), states.NV.fips, Census.ALL) 
countyNH = c.acs5.state_county(('B19058_002E'), states.NH.fips, Census.ALL) 
countyNJ = c.acs5.state_county(('B19058_002E'), states.NJ.fips, Census.ALL) 
countyNM = c.acs5.state_county(('B19058_002E'), states.NM.fips, Census.ALL) 
countyNY = c.acs5.state_county(('B19058_002E'), states.NY.fips, Census.ALL) 
countyNC = c.acs5.state_county(('B19058_002E'), states.NC.fips, Census.ALL) 
countyND = c.acs5.state_county(('B19058_002E'), states.ND.fips, Census.ALL) 
countyOH = c.acs5.state_county(('B19058_002E'), states.OH.fips, Census.ALL) 
countyOK = c.acs5.state_county(('B19058_002E'), states.OK.fips, Census.ALL) 
countyOR = c.acs5.state_county(('B19058_002E'), states.OR.fips, Census.ALL) 
countyPA = c.acs5.state_county(('B19058_002E'), states.PA.fips, Census.ALL) 
countyRI = c.acs5.state_county(('B19058_002E'), states.RI.fips, Census.ALL) 
countySC = c.acs5.state_county(('B19058_002E'), states.SC.fips, Census.ALL) 
countySD = c.acs5.state_county(('B19058_002E'), states.SD.fips, Census.ALL) 
countyTN = c.acs5.state_county(('B19058_002E'), states.TN.fips, Census.ALL) 
countyTX = c.acs5.state_county(('B19058_002E'), states.TX.fips, Census.ALL) 
countyUT = c.acs5.state_county(('B19058_002E'), states.UT.fips, Census.ALL) 
countyVT = c.acs5.state_county(('B19058_002E'), states.VT.fips, Census.ALL) 
countyVA = c.acs5.state_county(('B19058_002E'), states.VA.fips, Census.ALL) 
countyWA = c.acs5.state_county(('B19058_002E'), states.WA.fips, Census.ALL) 
countyWV = c.acs5.state_county(('B19058_002E'), states.WV.fips, Census.ALL) 
countyWI = c.acs5.state_county(('B19058_002E'), states.WI.fips, Census.ALL) 
countyWY = c.acs5.state_county(('B19058_002E'), states.WY.fips, Census.ALL) 



# create a single dataframe with all of the county level data
acs_countydf_S = pd.DataFrame(countyAL + countyAK + countyAZ +countyAR +countyCA +countyCO +countyCT +countyDE +countyFL +countyGA +countyHI +countyID +countyIL +countyIN +countyIA +countyKS 
                            +countyKY +countyLA +countyME +countyMD +countyMA +countyMI +countyMN +countyMS +countyMO +countyMT +countyNE +countyNV +countyNH +countyNJ +countyNM +countyNY 
                            +countyNC +countyND +countyOH +countyOK +countyOR +countyPA +countyRI +countySC +countySD +countyTN +countyTX +countyUT + countyVT +countyVA + countyWA +countyWV 
                            +countyWI +countyWY)


acs_countydf_S

      B19058_002E county state
0          1416.0    099    01
1          2297.0    079    01
2          7283.0    081    01
3          2021.0    093    01
4          1370.0    107    01
5          1614.0    119    01
6         40728.0    073    01
7          1409.0    023    01
8          2293.0    059    01
9          1971.0    091    01
10         4639.0    113    01
11         1899.0    019    01
12         2168.0    039    01
13         1002.0    041    01
14         5326.0    047    01
15         5516.0    077    01
16         1440.0    085    01
17         2237.0    087    01
18         4340.0    083    01
19         4533.0    117    01
20         4171.0    115    01
21         1500.0    133    01
22         6644.0    003    01
23         3897.0    043    01
24         4184.0    051    01
25         6066.0    069    01
26         2690.0    071    01
27         5647.0    121    01
28         7986.0    125    01
29          921.0    129    01
...           ...    ...   ...
3111       4077.0    039    55
3112       1098.0    053    55
3113       1141.0    049    55
3114        328.0    091    55
3115       1850.0    089    55
3116       2914.0    097    55
3117       1053.0    103    55
3118        838.0    005    56
3119        269.0    023    56
3120        124.0    019    56
3121       2841.0    025    56
3122       2991.0    021    56
3123        488.0    009    56
3124         79.0    027    56
3125        229.0    039    56
3126        883.0    037    56
3127        251.0    031    56
3128        593.0    033    56
3129        259.0    003    56
3130         59.0    011    56
3131        650.0    029    56
3132        694.0    001    56
3133        391.0    007    56
3134        514.0    015    56
3135        564.0    041    56
3136        265.0    043    56
3137        173.0    017    56
3138       1434.0    013    56
3139         97.0    035    56
3140        206.0    045    56

[3141 rows x 3 columns]

In [8]:
# export to csv combined raw data

acs_countydf_S.to_csv('./acs5_county_S.csv')

In [11]:
# B19058_002E - B19058. Public Assistance Income or Food Stamps/SNAP in the Past 12 Months for Households


c.acs5.state(('B19058_002E'), Census.ALL) 


# change to a dataframe using pandas

states_S = c.acs5.state(('B19058_002E'), Census.ALL) 

# create a single dataframe with all of the state level data
acs_statesdf_S = pd.DataFrame(states_S)


acs_statesdf_S

    B19058_002E state
0      4.79e+05    72
1      2.85e+05    01
2      3.28e+04    02
3      3.24e+05    04
4      1.61e+05    05
5      1.34e+06    06
6      1.86e+05    08
7      1.80e+05    09
8      4.22e+04    11
9      4.49e+04    10
10     1.13e+06    12
11     5.47e+05    13
12     5.61e+04    15
13     7.45e+04    16
14     6.70e+05    17
15     3.03e+05    18
16     1.48e+05    19
17     1.03e+05    20
18     2.86e+05    21
19     8.91e+04    23
20     2.85e+05    22
21     3.38e+05    25
22     2.52e+05    24
23     6.03e+05    26
24     2.03e+05    27
25     1.96e+05    28
26     3.05e+05    29
27     4.51e+04    30
28     6.97e+04    31
29     4.43e+04    33
30     1.38e+05    32
31     3.18e+05    34
32     1.35e+05    35
33     1.17e+06    36
34     5.50e+05    37
35     2.43e+04    38
36     6.89e+05    39
37     2.08e+05    40
38     2.92e+05    41
39     6.87e+05    42
40     6.99e+04    44
41     2.70e+05    45
42     3.87e+04    46
43     4.12e+05    47
44     1.24e+06    48
45     7.82e+04    49
46     3.54e+04    50
47     2.99e+05    51
48     1.26e+05    54
49     3.87e+05    53
50     1.49e+04    56
51     2.97e+05    55

In [12]:
# export to csv combined raw data

acs_statesdf_S.to_csv('./acs5_state_S.csv')